if !File.exists?('packed_flag')
  source 'https://rubygems.org'
end

gem 'fog'
gem "rake", '~> 10.1.0'
gem "streamingly", '~> 0.0.4'
gem "pipely", '~> 0.2.1'

group :development, :test do
  gem "rspec"
end
